# Generated by Django 4.1.4 on 2022-12-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "origin_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("si", "Single"), ("se", "Series")],
                        default="si",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("t", "Trailer"),
                            ("o", "Ongoing"),
                            ("c", "Completed"),
                        ],
                        default="t",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
                (
                    "on_theater",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "year",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lang",
                    models.CharField(
                        blank=True, default="Vietsub", max_length=100, null=True
                    ),
                ),
                (
                    "current_episode",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "episode_total",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "trailer_url",
                    models.CharField(blank=True, max_length=511, null=True),
                ),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=511, null=True),
                ),
                ("poster_url", models.CharField(blank=True, max_length=511, null=True)),
                (
                    "actors",
                    models.ManyToManyField(blank=True, null=True, to="movies.actor"),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, null=True, to="movies.category"),
                ),
                (
                    "directors",
                    models.ManyToManyField(blank=True, null=True, to="movies.director"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=4, null=True)),
                ("slug", models.SlugField(blank=True, max_length=4, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "embedded_link",
                    models.CharField(blank=True, max_length=511, null=True),
                ),
                ("m3u8_link", models.CharField(blank=True, max_length=511, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
