# Generated by Django 4.1.4 on 2022-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="thumbnail_url",
            new_name="thumb_url",
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="actors", to="movies.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="categories", to="movies.category"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="current_episode",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="directors", to="movies.director"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="episode_total",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("trailer", "Trailer"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                default="t",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("single", "Single"), ("series", "Series")],
                default="si",
                max_length=6,
                null=True,
            ),
        ),
    ]
