# Generated by Django 4.1.4 on 2022-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_actors_alter_movie_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="movies", to="movies.actor"
            ),
        ),
    ]
