# Generated by Django 4.1.4 on 2022-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_actors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="movies.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="categories",
            field=models.ManyToManyField(to="movies.category"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(to="movies.director"),
        ),
    ]
