# Generated by Django 4.1.4 on 2022-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_actors_alter_movie_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="categories",
            field=models.ManyToManyField(related_name="movies", to="movies.category"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(related_name="movies", to="movies.director"),
        ),
    ]
