# Generated by Django 4.1.4 on 2022-12-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_categories_alter_movie_directors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="embedded_link",
            new_name="link_embed",
        ),
        migrations.RenameField(
            model_name="episode",
            old_name="m3u8_link",
            new_name="link_m3u8",
        ),
    ]
